Update build-and-deploy.yml

diff --git a/.github/workflows/build-and-deploy.yml b/.github/workflows/build-and-deploy.yml
--- a/.github/workflows/build-and-deploy.yml
+++ b/.github/workflows/build-and-deploy.yml
@@ -27,7 +27,15 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Generate Docs Folder
-        run: node ./tools/build/build.js
+        run: 
+          echo "=== CURRENT WORKING DIRECTORY ==="
+          pwd
+          echo "=== LISTING FILES IN THE ROOT ==="
+          ls -la
+          echo "=== LISTING TOOLS/BUILD DIRECTORY ==="
+          ls -la tools/build || echo "tools/build folder not found!"
+          echo "=== RUNNING NODE SCRIPT ==="
+          node ./tools/build/build.js
       - name: Checkout
         uses: actions/checkout@v4
       - name: Setup Pages
